In [1]:
import numpy as np

In [2]:
N = 3
b = np.random.randint(-2000, 2000 + 1, size=(N,N))
stress = (b + b.T)/2
stress


array([[-1346. ,    45. ,  1469. ],
       [   45. , -1638. ,   236.5],
       [ 1469. ,   236.5,   588. ]])

In [3]:
prin_scalar, eig_vec = np.linalg.eig(stress)
prin = np.diag(prin_scalar)
prin, eig_vec

(array([[ 1397.0751709 ,     0.        ,     0.        ],
        [    0.        , -2148.34290789,     0.        ],
        [    0.        ,     0.        , -1644.73226301]]),
 array([[ 0.47171135,  0.86648064,  0.16340042],
        [ 0.07545011,  0.14496904, -0.98655525],
        [ 0.87851903, -0.47769789, -0.00300748]]))

In [4]:
eig_vec @ prin @ np.transpose(eig_vec), np.transpose(eig_vec) @ stress @ eig_vec, eig_vec@np.transpose(eig_vec)

(array([[-1346. ,    45. ,  1469. ],
        [   45. , -1638. ,   236.5],
        [ 1469. ,   236.5,   588. ]]),
 array([[ 1.39707517e+03, -1.13686838e-13,  9.37028233e-14],
        [-1.13686838e-13, -2.14834291e+03, -1.02140518e-12],
        [ 1.27897692e-13, -1.00053299e-12, -1.64473226e+03]]),
 array([[ 1.00000000e+00, -5.82867088e-16, -2.01661604e-16],
        [-5.82867088e-16,  1.00000000e+00,  8.67361738e-18],
        [-2.01661604e-16,  8.67361738e-18,  1.00000000e+00]]))

In [5]:
#B_in = np.array( [ [ -0.225, 0.39, 0.23], [-0.093, 0.41, 0.075], [ -0.258, 0.512, 0.139] ])*5.298
B_in = np.array( [ [ 2, .7, 7 ], [.7,1,0], [ 7,0,1] ])
transformed_principal_stress = np.diag(B_in @ prin_scalar)
transformed_principal_stress, B_in @ prin_scalar #, np.linalg.eig(transformed_principal_stress)

(array([[-10222.81553477,      0.        ,      0.        ],
        [     0.        ,  -1170.39028826,      0.        ],
        [     0.        ,      0.        ,   8134.79393328]]),
 array([-10222.81553477,  -1170.39028826,   8134.79393328]))

In [6]:
return_stress = eig_vec @ transformed_principal_stress @ np.transpose(eig_vec)
return_stress

array([[-2936.21432493, -1822.21058526, -3755.96479553],
       [-1822.21058526,  7834.73124645,  -572.42527839],
       [-3755.96479553,  -572.42527839, -8156.92881128]])

In [7]:
rprin, reig_vec = np.linalg.eig(return_stress)
rprin, reig_vec

(array([-10222.81553477,  -1170.39028826,   8134.79393328]),
 array([[-0.47171135, -0.86648064,  0.16340042],
        [-0.07545011, -0.14496904, -0.98655525],
        [-0.87851903,  0.47769789, -0.00300748]]))

In [8]:
Beta = eig_vec @ B_in @ np.transpose(eig_vec)
Beta

array([[ 2.87382154, -3.04206273,  1.78444835],
       [-3.04206273, -0.02109403, -5.93833594],
       [ 1.78444835, -5.93833594,  1.14727249]])

In [9]:
A = np.einsum('im,nj->ijmn', Beta, np.eye(3))
np.tensordot(A, stress)

array([[-1383.70198107,  5534.24275274,  4551.451635  ],
       [-4629.74829819, -1506.75725375, -7965.52041859],
       [ -983.74931091, 10078.6243927 ,  1891.53440572]])

In [10]:
np.cross(np.eye(3), np.array([1,2,3]))

array([[ 0., -3.,  2.],
       [ 3.,  0., -1.],
       [-2.,  1.,  0.]])