In [1]:
import numpy as np

In [2]:
B = np.array( [ [ -0.225, 0.39, 0.23], [-0.093, 0.41, 0.075], [ -0.258, 0.512, 0.139] ])*5.298
A = np.linalg.inv(B)

In [3]:
sv = np.random.rand(6)*1000
stress_tensor = np.array([[sv[0], sv[5], sv[4]], [ sv[5], sv[1], sv[3] ], [ sv[4], sv[3], sv[2] ] ])
stress_tensor

array([[114.09655358, 222.55330183, 910.30498689],
       [222.55330183, 472.04809018, 834.11296747],
       [910.30498689, 834.11296747, 301.74157596]])

In [4]:
princ, p_vec = np.linalg.eig(stress_tensor)
princ, p_vec

(array([1652.60265709,   92.64884033, -857.3652777 ]),
 array([[-0.47917583, -0.64493454, -0.59535701],
        [-0.56494313,  0.74574038, -0.35314379],
        [-0.67173639, -0.16712488,  0.72169211]]))

In [6]:
B_four = np.einsum('ik,jl->ijkl', np.eye(3), B)

In [9]:
trans_tens = np.tensordot(B_four, np.diag(princ))
trans_tens

array([[-1969.98499739,  -814.26046559, -2258.91613034],
       [  191.43288686,   201.24995798,   251.31702069],
       [-1044.73388549,  -340.67409309,  -631.38265253]])

In [11]:
np.tensordot(np.linalg.tensorinv(B_four), trans_tens)

array([[ 1.65260266e+03,  5.68434189e-14,  4.54747351e-13],
       [-9.94759830e-14,  9.26488403e+01,  0.00000000e+00],
       [-2.27373675e-13, -1.42108547e-14, -8.57365278e+02]])

In [12]:
princ_trans, p_vec_trans = np.linalg.eig(trans_tens)
princ_trans, p_vec_trans

(array([-2898.11299688,   379.1388781 ,   118.85642683]),
 array([[ 0.9095915 , -0.713767  , -0.19339173],
        [-0.08908938,  0.18588639,  0.96636733],
        [ 0.40584034,  0.67526507, -0.16951052]]))

In [13]:
B @ princ

array([-2823.28599602,  -953.6846007 , -2638.98176218])