In [1]:
import numpy as np
import csv


In [2]:
H = 5
G = 2
F = 1.5
N = 1.25
L = 1.25
M = 1.25
transform_matrix = np.array( [ [ (H+G), -H, -G, 0, 0, 0 ], [ -H, (F+H), -F, 0, 0, 0 ], [ -G, -F, (F+G), 0, 0, 0 ], [ 0, 0, 0, 2*N, 0, 0 ], [ 0, 0, 0, 0, 2*L, 0], [ 0, 0, 0, 0, 0, 2*M] ])

In [3]:
display(transform_matrix)

array([[ 7. , -5. , -2. ,  0. ,  0. ,  0. ],
       [-5. ,  6.5, -1.5,  0. ,  0. ,  0. ],
       [-2. , -1.5,  3.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  2.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  2.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  2.5]])

In [4]:
def von_mises_stress(voigt_stress):
    sigma_11 = voigt_stress[0]
    sigma_22 = voigt_stress[1]
    sigma_33 = voigt_stress[2]
    sigma_23 = voigt_stress[3]
    sigma_13 = voigt_stress[4]
    sigma_12 = voigt_stress[5]
    vm_sq = 1/2*( (sigma_11 - sigma_22)**2 + (sigma_22 - sigma_33)**2 + (sigma_33 - sigma_11)**2 + 6*(sigma_23**2 + sigma_13**2 + sigma_12**2) )
    return np.sqrt(vm_sq)
axial_and_shear_pairs = []
for uniax in np.linspace(0,1,5):
    equiv_shear = np.sqrt((1. - uniax**2)/3)
    axial_and_shear_pairs.append([uniax, equiv_shear])



In [5]:
s11_12 = [ [s11, 0, 0, s12, 0, 0] for s11, s12 in axial_and_shear_pairs ]
s11_13 = [ [s11, 0, 0, 0, 0, s13] for s11, s13 in axial_and_shear_pairs ]
s11_23 = [ [s11, 0, 0, 0, s23, 0] for s11, s23 in axial_and_shear_pairs ]
s22_12 = [ [0, s22, 0, s12, 0, 0] for s22, s12 in axial_and_shear_pairs ]
s22_13 = [ [0, s22, 0, 0, 0, s13] for s22, s13 in axial_and_shear_pairs ]
s22_23 = [ [0, s22, 0, 0, s23, 0] for s22, s23 in axial_and_shear_pairs ]
s33_12 = [ [0, 0, s33, s12, 0, 0] for s33, s12 in axial_and_shear_pairs ]
s33_13 = [ [0, 0, s33, 0, 0, s13] for s33, s13 in axial_and_shear_pairs ]
s33_23 = [ [0, 0, s33, 0, s23, 0] for s33, s23 in axial_and_shear_pairs ]
all_stress_combos = s11_12 + s11_13 + s11_23 + s22_12 + s22_13 + s22_23 + s33_12 + s33_13 + s33_23
for s in all_stress_combos: 
    vm_stress = von_mises_stress(s)
    assert(vm_stress == 1.0)

In [6]:
stresses = []
for stress in all_stress_combos:
    stress = np.array(stress)
    new_yield_stress = transform_matrix @ stress
    stresses.append(list(new_yield_stress))
stresses = np.array(stresses)
print(stresses)


# with open('epvm_eq_0.csv', 'wb') as myfile:
#     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
#     wr.writerow(stresses)

np.savetxt('epvm_eq_0.csv', stresses, delimiter=",")

[[ 0.          0.          0.          1.44337567  0.          0.        ]
 [ 1.75       -1.25       -0.5         1.39754249  0.          0.        ]
 [ 3.5        -2.5        -1.          1.25        0.          0.        ]
 [ 5.25       -3.75       -1.5         0.95470327  0.          0.        ]
 [ 7.         -5.         -2.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.44337567]
 [ 1.75       -1.25       -0.5         0.          0.          1.39754249]
 [ 3.5        -2.5        -1.          0.          0.          1.25      ]
 [ 5.25       -3.75       -1.5         0.          0.          0.95470327]
 [ 7.         -5.         -2.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.44337567  0.        ]
 [ 1.75       -1.25       -0.5         0.          1.39754249  0.        ]
 [ 3.5        -2.5        -1.          0.          1.25        0.        ]
 [ 5.25       -3.75      

In [7]:
stresses_evmp = []
for stress in all_stress_combos:
    stress = np.array(stress)
    new_yield_stress = (1.1*transform_matrix) @ stress
    stresses_evmp.append(list(new_yield_stress))
stresses_evmp = np.array(stresses_evmp)
print(stresses_evmp)

np.savetxt('epvm_deq_0.csv', stresses_evmp, delimiter=",")

[[ 0.          0.          0.          1.58771324  0.          0.        ]
 [ 1.925      -1.375      -0.55        1.53729673  0.          0.        ]
 [ 3.85       -2.75       -1.1         1.375       0.          0.        ]
 [ 5.775      -4.125      -1.65        1.0501736   0.          0.        ]
 [ 7.7        -5.5        -2.2         0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.58771324]
 [ 1.925      -1.375      -0.55        0.          0.          1.53729673]
 [ 3.85       -2.75       -1.1         0.          0.          1.375     ]
 [ 5.775      -4.125      -1.65        0.          0.          1.0501736 ]
 [ 7.7        -5.5        -2.2         0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.58771324  0.        ]
 [ 1.925      -1.375      -0.55        0.          1.53729673  0.        ]
 [ 3.85       -2.75       -1.1         0.          1.375       0.        ]
 [ 5.775      -4.125     

In [8]:
stresses_evmp = []
for stress in all_stress_combos:
    stress = np.array(stress)
    new_yield_stress = (1.2*transform_matrix) @ stress
    stresses_evmp.append(list(new_yield_stress))
stresses_evmp = np.array(stresses_evmp)
print(stresses_evmp)

np.savetxt('epvm_deq_1.csv', stresses_evmp, delimiter=",")

[[ 0.          0.          0.          1.73205081  0.          0.        ]
 [ 2.1        -1.5        -0.6         1.67705098  0.          0.        ]
 [ 4.2        -3.         -1.2         1.5         0.          0.        ]
 [ 6.3        -4.5        -1.8         1.14564392  0.          0.        ]
 [ 8.4        -6.         -2.4         0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.73205081]
 [ 2.1        -1.5        -0.6         0.          0.          1.67705098]
 [ 4.2        -3.         -1.2         0.          0.          1.5       ]
 [ 6.3        -4.5        -1.8         0.          0.          1.14564392]
 [ 8.4        -6.         -2.4         0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.73205081  0.        ]
 [ 2.1        -1.5        -0.6         0.          1.67705098  0.        ]
 [ 4.2        -3.         -1.2         0.          1.5         0.        ]
 [ 6.3        -4.5       

In [9]:
stresses_evmp = []
for stress in all_stress_combos:
    stress = np.array(stress)
    new_yield_stress = (1.3*transform_matrix) @ stress
    stresses_evmp.append(list(new_yield_stress))
stresses_evmp = np.array(stresses_evmp)
print(stresses_evmp)

np.savetxt('epvm_deq_2.csv', stresses_evmp, delimiter=",")

[[ 0.          0.          0.          1.87638837  0.          0.        ]
 [ 2.275      -1.625      -0.65        1.81680523  0.          0.        ]
 [ 4.55       -3.25       -1.3         1.625       0.          0.        ]
 [ 6.825      -4.875      -1.95        1.24111425  0.          0.        ]
 [ 9.1        -6.5        -2.6         0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.87638837]
 [ 2.275      -1.625      -0.65        0.          0.          1.81680523]
 [ 4.55       -3.25       -1.3         0.          0.          1.625     ]
 [ 6.825      -4.875      -1.95        0.          0.          1.24111425]
 [ 9.1        -6.5        -2.6         0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.87638837  0.        ]
 [ 2.275      -1.625      -0.65        0.          1.81680523  0.        ]
 [ 4.55       -3.25       -1.3         0.          1.625       0.        ]
 [ 6.825      -4.875     

In [10]:
stresses_evmp = []
for stress in all_stress_combos:
    stress = np.array(stress)
    new_yield_stress = (1.4*transform_matrix) @ stress
    stresses_evmp.append(list(new_yield_stress))
stresses_evmp = np.array(stresses_evmp)
print(stresses_evmp)

np.savetxt('epvm_deq_4.csv', stresses_evmp, delimiter=",")

[[ 0.          0.          0.          2.02072594  0.          0.        ]
 [ 2.45       -1.75       -0.7         1.95655948  0.          0.        ]
 [ 4.9        -3.5        -1.4         1.75        0.          0.        ]
 [ 7.35       -5.25       -2.1         1.33658458  0.          0.        ]
 [ 9.8        -7.         -2.8         0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          2.02072594]
 [ 2.45       -1.75       -0.7         0.          0.          1.95655948]
 [ 4.9        -3.5        -1.4         0.          0.          1.75      ]
 [ 7.35       -5.25       -2.1         0.          0.          1.33658458]
 [ 9.8        -7.         -2.8         0.          0.          0.        ]
 [ 0.          0.          0.          0.          2.02072594  0.        ]
 [ 2.45       -1.75       -0.7         0.          1.95655948  0.        ]
 [ 4.9        -3.5        -1.4         0.          1.75        0.        ]
 [ 7.35       -5.25      