In [1]:
import sympy as sp
from numpy import array
import numpy as np
from sympy import init_printing
init_printing(use_latex='mathjax')


In [2]:
X_0 = sp.Symbol('X_0')
full_eq =  (array([[ 0.12128007,  0.04931317,  0.        ,  0.        ,  0.        ],
       [ 0.04931317, -0.17241282,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.10697085,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.10697085,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.08995117]]) + (array([[-0.05967189, -0.0295037 ,  0.        ,  0.        ,  0.        ],
       [-0.0295037 ,  0.08576931,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.05362774,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.05362774,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.04509522]])) * ((X_0)/(array([[0.01029129]]) + X_0)  + (X_0)/(array([[0.01029129]]) + X_0) )) @ (array([[ 0.12128007,  0.04931317,  0.        ,  0.        ,  0.        ],
       [ 0.04931317, -0.17241282,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.10697085,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.10697085,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.08995117]]) + (array([[-0.05967189, -0.0295037 ,  0.        ,  0.        ,  0.        ],
       [-0.0295037 ,  0.08576931,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.05362774,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.05362774,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.04509522]])) * ((X_0)/(array([[0.01029129]]) + X_0)  + (X_0)/(array([[0.01029129]]) + X_0) ))

full_eq

array([[0.00348187325476*(-X_0/(X_0 + 0.01029129) + 0.835711622610046)**2 + 0.0147088553792049*(-0.984034557367917*X_0/(X_0 + 0.01029129) + 1)**2,
        (-0.11934378*X_0/(X_0 + 0.01029129) + 0.12128007)*(-0.0590074*X_0/(X_0 + 0.01029129) + 0.04931317) + (-0.0590074*X_0/(X_0 + 0.01029129) + 0.04931317)*(0.17153862*X_0/(X_0 + 0.01029129) - 0.17241282),
        0, 0, 0],
       [(-0.11934378*X_0/(X_0 + 0.01029129) + 0.12128007)*(-0.0590074*X_0/(X_0 + 0.01029129) + 0.04931317) + (-0.0590074*X_0/(X_0 + 0.01029129) + 0.04931317)*(0.17153862*X_0/(X_0 + 0.01029129) - 0.17241282),
        0.00348187325476*(-X_0/(X_0 + 0.01029129) + 0.835711622610046)**2 + 0.0297261805003524*(0.994929611382727*X_0/(X_0 + 0.01029129) - 1)**2,
        0, 0, 0],
       [0, 0,
        0.0115037379900304*(X_0/(X_0 + 0.01029129) - 0.997346242821346)**2,
        0, 0],
       [0, 0, 0,
        0.0115037379900304*(X_0/(X_0 + 0.01029129) - 0.997346242821346)**2,
        0],
       [0, 0, 0, 0,
        0.008134315467393

In [3]:
test = sp.Matrix(full_eq)
test

⎡                                                                   2         
⎢                            ⎛         X₀                          ⎞          
⎢           0.00348187325476⋅⎜- ─────────────── + 0.835711622610046⎟  + 0.0147
⎢                            ⎝  X₀ + 0.01029129                    ⎠          
⎢                                                                             
⎢                                                                             
⎢⎛   0.11934378⋅X₀              ⎞ ⎛    0.0590074⋅X₀              ⎞   ⎛    0.05
⎢⎜- ─────────────── + 0.12128007⎟⋅⎜- ─────────────── + 0.04931317⎟ + ⎜- ──────
⎢⎝  X₀ + 0.01029129             ⎠ ⎝  X₀ + 0.01029129             ⎠   ⎝  X₀ + 0
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                   

In [4]:
test_0 = test.subs({X_0: 0})
test_0

⎡0.0171406441146538   -0.0025215179933175          0                   0      
⎢                                                                             
⎢-0.0025215179933175  0.0321579692358013           0                   0      
⎢                                                                             
⎢         0                    0           0.0114427627497225          0      
⎢                                                                             
⎢         0                    0                   0           0.0114427627497
⎢                                                                             
⎣         0                    0                   0                   0      

             0         ⎤
                       ⎥
             0         ⎥
                       ⎥
             0         ⎥
                       ⎥
225          0         ⎥
                       ⎥
     0.0080912129843689⎦

In [5]:
P_vm_nat = 3./2.*np.eye(5)
P_vm_nat

array([[1.5, 0. , 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. , 0. ],
       [0. , 0. , 1.5, 0. , 0. ],
       [0. , 0. , 0. , 1.5, 0. ],
       [0. , 0. , 0. , 0. , 1.5]])

In [6]:
M = (test_0.T @ P_vm_nat @ test_0)
M

⎡ 0.00045023960048376   -0.000186461010913162           0                     
⎢                                                                             
⎢-0.000186461010913162   0.00156073955754205            0                     
⎢                                                                             
⎢          0                      0            0.000196405229019655           
⎢                                                                             
⎢          0                      0                     0            0.0001964
⎢                                                                             
⎣          0                      0                     0                     

0                     0         ⎤
                                ⎥
0                     0         ⎥
                                ⎥
0                     0         ⎥
                                ⎥
05229019655           0         ⎥
                                ⎥
0            9.8

In [7]:
M_upgrade = np.zeros(((6,6)))
M_upgrade[1:, 1:] = M
M_upgrade

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.50239600e-04, -1.86461011e-04,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.86461011e-04,  1.56073956e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.96405229e-04,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.96405229e-04,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  9.82015913e-05]])

In [26]:
sqrt2 = np.sqrt(2)
sqrt3 = np.sqrt(3)
d = 1./np.sqrt(6) * np.array( [[ sqrt2, sqrt2, sqrt2, 0, 0, 0  ],
                                   [ -1, -1, 2, 0, 0, 0],
                                   [-sqrt3, sqrt3, 0, 0, 0, 0],
                                   [0, 0, 0, 2*sqrt3, 0, 0],
                                   [0, 0, 0, 0, 2*sqrt3, 0],
                                   [0, 0, 0, 0, 0, 2*sqrt3] ])
d_inv = 1/np.sqrt(6) * np.array( [[ sqrt2, -1, -sqrt3, 0, 0, 0  ],
                                   [ sqrt2, -1, sqrt3, 0, 0, 0],
                                   [ sqrt2, 2, 0, 0, 0, 0],
                                   [0, 0, 0, sqrt3, 0, 0],
                                   [0, 0, 0, 0, sqrt3, 0],
                                   [0, 0, 0, 0, 0, sqrt3] ])
real_space = d.T @ M_upgrade @ d
real_space*10**2

array([[ 0.07477564, -0.07053298, -0.00424266,  0.        ,  0.        ,
         0.        ],
       [-0.07053298,  0.0963063 , -0.02577332,  0.        ,  0.        ,
         0.        ],
       [-0.00424266, -0.02577332,  0.03001597,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.03928105,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.03928105,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.01964032]])

In [23]:
np.linalg.eig(real_space)[0]*100

array([ 1.59121157e-01, -1.85103205e-17,  4.19767591e-02,  3.92810458e-02,
        3.92810458e-02,  1.96403183e-02])

In [10]:
mapping_matrices = []
number_of_eqps = 6
eqpses = np.linspace(0, 0.05, number_of_eqps)
for eqps in eqpses:
    temp = sp.Matrix(full_eq).subs({X_0: eqps})
    mapping_matrices.append(np.array(temp, dtype=float))
mapping_matrices = np.array(mapping_matrices)
P_mapped = mapping_matrices.transpose((0, 2, 1)) @ P_vm_nat @ mapping_matrices
P_mapped

array([[[ 4.50239600e-04, -1.86461011e-04,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [-1.86461011e-04,  1.56073956e-03,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.96405229e-04,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.96405229e-04,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  9.82015913e-05]],

       [[ 2.82764738e-05, -9.59546644e-06,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [-9.59546644e-06,  9.95747304e-05,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.28616410e-05,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.28616410e-05,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  

In [11]:
def remove_hydrostatic_dependence(data, transpose_data):
    # Get the rotation matrix with full precision


    d = 1./np.sqrt(6) * np.array( [[ sqrt2, sqrt2, sqrt2, 0, 0, 0  ],
                                   [ -1, -1, 2, 0, 0, 0],
                                   [-sqrt3, sqrt3, 0, 0, 0, 0],
                                   [0, 0, 0, 2*sqrt3, 0, 0],
                                   [0, 0, 0, 0, 2*sqrt3, 0],
                                   [0, 0, 0, 0, 0, 2*sqrt3] ])

    # Isolate stress
    stress_vectors = data[:,0:6]
    stress_vectors_T = transpose_data[:, 0:6]

    # # Shift the X_0 up a tiny bit
    # data[:,6] += 1e-6
    # transpose_data[:,6] += 1e-6

    # Rotate to natural basis
    stress_vectors = (d @ stress_vectors.T).T
    stress_vectors_T = (d @ stress_vectors_T.T).T
    #print(np.shape(stress_vectors_T), np.shape(transpose_data[:,3].T))

    # We assert that there should be hydrostatic stress independence. Therefore, we only solve for the 5x5 submatrix
    data = np.column_stack([stress_vectors[:,1:6], data[:,6].T ])
    transpose_data = np.column_stack( [stress_vectors_T[:, 1:6], transpose_data[:,6].T ])

    return data, transpose_data

data_path = "../data_6x6/processed_data/transverse_iso_6x6_bingo.csv"
transposed_data_path = "../data_6x6/processed_data/transverse_iso_6x6_bingo_transpose.csv"
data_pre = np.loadtxt(data_path)
transposed_data_pre = np.loadtxt(transposed_data_path)
data, transpose_data = remove_hydrostatic_dependence(data_pre, transposed_data_pre)

In [12]:

for train_data in data:
    eqps = train_data[5]
    temp = sp.Matrix(full_eq).subs({X_0: eqps})
    mapping_matrix = np.array(temp, dtype=float)
    P_mapped = mapping_matrix.T @ P_vm_nat @ mapping_matrix
    yield_stresses = train_data[0:5]
    yield_stress = yield_stresses @ P_mapped @ yield_stresses
    print(yield_stress)

1.1132917763481207
1.1023590738743276
1.0669269853170211
1.0371043917587743
1.0180699475910546
1.0112193171777901
nan
1.1513243484417666
1.1129492316704126
1.0711443130219656
1.0389567997866078
1.0188499026322848
1.0114615371515108
nan
0.9614252045626362
0.9741547987752023
0.9641771545532579
0.9672527324774477
0.9899904606131961
1.035046849156011
nan
1.0397388291461642
0.9967451958535102
0.9734101333547068
0.9713227100500152
0.9915777503250196
1.035274764859786
nan
0.9811564868383489
1.0083930110351065
1.010594581708208
1.0064412948992403
0.9997635481487191
0.99185501859626
nan
0.9811564868383489
1.0083930110351065
1.010594581708208
1.0064412948992403
0.9997635481487191
0.99185501859626
nan
0.9811564868383489
1.0083930110351065
1.010594581708208
1.0064412948992403
0.9997635481487191
0.99185501859626
nan
0.9811564868383489
1.0083930110351065
1.010594581708208
1.0064412948992403
0.9997635481487191
0.99185501859626
nan
0.9811463420860075
1.0083857322448928
1.0105905255773315
1.00644050229

In [13]:
for train_data in data_pre:
    eqps = train_data[6]
    temp = sp.Matrix(full_eq).subs({X_0: eqps})
    mapping_matrix = np.array(temp, dtype=float)
    P_mapped = mapping_matrix.T @ P_vm_nat @ mapping_matrix
    P_upgrade = np.zeros(((6,6)))
    P_upgrade[1:, 1:] = P_mapped
    P_lab = d.T @ P_upgrade @ d
    yield_stresses = train_data[0:6]
    yield_stress = yield_stresses @ P_lab @ yield_stresses
    print(yield_stress)

1.1132917763481205
1.1023590738743276
1.066926985317021
1.0371043917587746
1.0180699475910546
1.0112193171777901
nan
1.1513243484417668
1.1129492316704128
1.0711443130219653
1.0389567997866078
1.0188499026322848
1.0114615371515108
nan
0.9614252045626364
0.9741547987752021
0.9641771545532579
0.9672527324774478
0.9899904606131962
1.0350468491560112
nan
1.0397388291461644
0.9967451958535101
0.9734101333547069
0.9713227100500154
0.9915777503250198
1.035274764859786
nan
0.9811564868383489
1.0083930110351063
1.0105945817082078
1.0064412948992403
0.9997635481487189
0.9918550185962597
nan
0.9811564868383489
1.0083930110351063
1.0105945817082078
1.0064412948992403
0.9997635481487189
0.9918550185962597
nan
0.9811564868383489
1.0083930110351063
1.0105945817082078
1.0064412948992403
0.999763548148719
0.9918550185962597
nan
0.9811564868383489
1.0083930110351063
1.0105945817082078
1.0064412948992403
0.999763548148719
0.9918550185962597
nan
0.9811463420860074
1.0083857322448928
1.0105905255773318
1.0

In [46]:
for train_data in data_pre:
    eqps = train_data[6]
    temp = sp.Matrix(full_eq).subs({X_0: eqps})
    mapping_matrix = np.array(temp, dtype=float)
    P_mapped = mapping_matrix.T @ P_vm_nat @ mapping_matrix
    mapp_inv = np.linalg.inv(mapping_matrix)
    recover_P = mapp_inv.T @ P_mapped @ mapp_inv
    P_upgrade = np.zeros(((6,6)))
    P_upgrade[1:, 1:] = P_mapped
    P_lab = d.T @ P_upgrade @ d
    print(P_lab)


[[ 7.47756397e-04 -7.05329845e-04 -4.24265520e-05  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.05329845e-04  9.63063027e-04 -2.57733182e-04  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.24265520e-05 -2.57733182e-04  3.00159734e-04  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.92810458e-04
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   3.92810458e-04  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.96403183e-04]]
[[ 4.89601657e-05 -4.50746196e-05 -3.88554614e-06  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.50746196e-05  6.00400560e-05 -1.49654364e-05  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.88554614e-06 -1.49654364e-05  1.88509825e-05  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.57232819e-05
   0.00000000e+00  0.000

In [30]:
S = sp.symbols(['\sigma_11', '\sigma_22', '\sigma_33', '\sigma_23', '\sigma_13', '\sigma_12']) 
sig_symbols = sp.Matrix( [ S[0], S[1], S[2], S[3], S[4], S[5] ] )
sig_symbols

⎡\sigma₁₁⎤
⎢        ⎥
⎢\sigma₂₂⎥
⎢        ⎥
⎢\sigma₃₃⎥
⎢        ⎥
⎢\sigma₂₃⎥
⎢        ⎥
⎢\sigma₁₃⎥
⎢        ⎥
⎣\sigma₁₂⎦

In [42]:
for eqps in eqpses:
    temp = sp.Matrix(full_eq).subs({X_0: eqps})
    mapping_matrix = np.array(temp, dtype=float)
    P_mapped = mapping_matrix.T @ P_vm_nat @ mapping_matrix
    P_upgrade = np.zeros(((6,6)))
    P_upgrade[1:, 1:] = P_mapped
    P_lab = d.T @ P_upgrade @ d
    yield_F = sig_symbols.T @ P_upgrade @ sig_symbols
    yield_F = yield_F[0,0]
    yield_F = yield_F.simplify()
    print(yield_F)


9.82015913376298e-5*\sigma_12**2 + 0.000196405229019655*\sigma_13**2 + 0.00045023960048376*\sigma_22**2 - 0.000372922021826324*\sigma_22*\sigma_33 + 0.000196405229019655*\sigma_23**2 + 0.00156073955754205*\sigma_33**2
6.43077401539629e-6*\sigma_12**2 + 1.28616409585752e-5*\sigma_13**2 + 2.82764738038919e-5*\sigma_22**2 - 1.9190932877682e-5*\sigma_22*\sigma_33 + 1.28616409585752e-5*\sigma_23**2 + 9.95747304458002e-5*\sigma_33**2
1.28151362055291e-6*\sigma_12**2 + 2.56303753113046e-6*\sigma_13**2 + 5.52809273560752e-6*\sigma_22**2 - 2.85730130348326e-6*\sigma_22*\sigma_33 + 2.56303753113046e-6*\sigma_23**2 + 1.95529925492621e-5*\sigma_33**2
4.05163494285038e-7*\sigma_12**2 + 8.10327626806062e-7*\sigma_13**2 + 1.7559096688782e-6*\sigma_22**2 - 6.14800066335102e-7*\sigma_22*\sigma_33 + 8.10327626806062e-7*\sigma_23**2 + 6.16368081524238e-6*\sigma_33**2
1.65185834900982e-7*\sigma_12**2 + 3.30370858281329e-7*\sigma_13**2 + 7.36656213015277e-7*\sigma_22**2 - 1.37422251951995e-7*\sigma_22*\sig

In [45]:
H = 7
G = 1.5
F = 1.5
N = 1
L = 2
M = 2
P = np.array( [ [ G+H, -H, -G, 0, 0, 0 ],
                [-H, F+H, -F, 0,0,0],
                 [-G, -F, F+G, 0, 0, 0],
                  [0,0,0, 2*L, 0, 0],
                   [0,0,0,0, 2*M, 0],
                    [0,0,0,0,0,2*N] ])
for eqps in eqpses:
    P_analytical = P/(10 + 990*eqps)**2
    
    temp = sp.Matrix(full_eq).subs({X_0: eqps})
    mapping_matrix = np.array(temp, dtype=float)
    P_mapped = mapping_matrix.T @ P_vm_nat @ mapping_matrix
    P_upgrade = np.zeros(((6,6)))
    P_upgrade[1:, 1:] = P_mapped
    P_lab = d.T @ P_upgrade @ d

    print(P_analytical)

[[ 0.085 -0.07  -0.015  0.     0.     0.   ]
 [-0.07   0.085 -0.015  0.     0.     0.   ]
 [-0.015 -0.015  0.03   0.     0.     0.   ]
 [ 0.     0.     0.     0.04   0.     0.   ]
 [ 0.     0.     0.     0.     0.04   0.   ]
 [ 0.     0.     0.     0.     0.     0.02 ]]
[[ 0.0214641  -0.01767632 -0.00378778  0.          0.          0.        ]
 [-0.01767632  0.0214641  -0.00378778  0.          0.          0.        ]
 [-0.00378778 -0.00378778  0.00757557  0.          0.          0.        ]
 [ 0.          0.          0.          0.01010076  0.          0.        ]
 [ 0.          0.          0.          0.          0.01010076  0.        ]
 [ 0.          0.          0.          0.          0.          0.00505038]]
[[ 0.00957164 -0.00788253 -0.00168911  0.          0.          0.        ]
 [-0.00788253  0.00957164 -0.00168911  0.          0.          0.        ]
 [-0.00168911 -0.00168911  0.00337823  0.          0.          0.        ]
 [ 0.          0.          0.          0.0045043   0.

In [50]:
for eqps in eqpses:
    temp = sp.Matrix(full_eq).subs({X_0: eqps})
    mapping_matrix = np.array(temp, dtype=float)
    P_mapped = mapping_matrix.T @ P_vm_nat @ mapping_matrix
    P_upgrade = np.zeros(((6,6)))
    P_upgrade[1:, 1:] = P_mapped
    P_lab = d.T @ P_upgrade @ d
    print(P_lab)


[[ 7.47756397e-04 -7.05329845e-04 -4.24265520e-05  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.05329845e-04  9.63063027e-04 -2.57733182e-04  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.24265520e-05 -2.57733182e-04  3.00159734e-04  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.92810458e-04
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   3.92810458e-04  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.96403183e-04]]
[[ 4.89601657e-05 -4.50746196e-05 -3.88554614e-06  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.50746196e-05  6.00400560e-05 -1.49654364e-05  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.88554614e-06 -1.49654364e-05  1.88509825e-05  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.57232819e-05
   0.00000000e+00  0.000