In [5]:
import sympy as sp
from numpy import array
import numpy as np
from sympy import init_printing
init_printing(use_latex='mathjax')


In [14]:
X_0 = sp.Symbol('X_0')
full_eq = (array([[ 7.28704052e+01, -7.29120512e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-7.29120512e+01,  7.28715924e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  6.13735219e-02,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.29449673e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.93094605e-01]]) + (X_0) * (array([[ 3.06683633, -3.61548079,  0.        ,  0.        ,  0.        ],
       [-3.61548079,  3.05104504,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.75963905,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -2.05218189,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -1.70980201]]))) @ (array([[ 7.28704052e+01, -7.29120512e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-7.29120512e+01,  7.28715924e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  6.13735219e-02,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.29449673e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.93094605e-01]]) + (X_0) * (array([[ 3.06683633, -3.61548079,  0.        ,  0.        ,  0.        ],
       [-3.61548079,  3.05104504,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.75963905,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -2.05218189,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -1.70980201]])))
full_eq

array([[5316.16721019142*(-0.0495868752901029*X_0 - 1)**2 + 5310.09595401219*(0.0420861709439211*X_0 + 1)**2,
        (-3.61548079*X_0 - 72.9120512)*(3.05104504*X_0 + 72.8715924) + (-3.61548079*X_0 - 72.9120512)*(3.06683633*X_0 + 72.8704052),
        0, 0, 0],
       [(-3.61548079*X_0 - 72.9120512)*(3.05104504*X_0 + 72.8715924) + (-3.61548079*X_0 - 72.9120512)*(3.06683633*X_0 + 72.8704052),
        5316.16721019142*(-0.0495868752901029*X_0 - 1)**2 + 5310.26897891174*(0.041868785071314*X_0 + 1)**2,
        0, 0, 0],
       [0, 0, 0.577051486284902*(0.0807930054412026 - X_0)**2, 0, 0],
       [0, 0, 0, 4.21145050964397*(0.111807668763708 - X_0)**2, 0],
       [0, 0, 0, 0, 2.92342291340004*(0.112933897533551 - X_0)**2]],
      dtype=object)

In [15]:
test = sp.Matrix(full_eq)
test

⎡                                                         2                   
⎢            5316.16721019142⋅(-0.0495868752901029⋅X₀ - 1)  + 5310.09595401219
⎢                                                                             
⎢                                                                             
⎢(-3.61548079⋅X₀ - 72.9120512)⋅(3.05104504⋅X₀ + 72.8715924) + (-3.61548079⋅X₀ 
⎢                                                                             
⎢                                                                             
⎢                                                           0                 
⎢                                                                             
⎢                                                                             
⎢                                                           0                 
⎢                                                                             
⎢                                                   

In [17]:
test_0 = test.subs({X_0: 9.00000000e-06})
test_0

⎡10626.2719318925   -10626.3567479553           0                   0         
⎢                                                                             
⎢-10626.3567479553  10626.4449361443            0                   0         
⎢                                                                             
⎢        0                  0          0.00376587004612127          0         
⎢                                                                             
⎢        0                  0                   0           0.0526386770765897
⎢                                                                             
⎣        0                  0                   0                   0         

          0         ⎤
                    ⎥
          0         ⎥
                    ⎥
          0         ⎥
                    ⎥
          0         ⎥
                    ⎥
  0.0372795839531158⎦

In [8]:
stress = sp.Matrix([0, 1000, 0])

In [19]:
transformed_stress = test_0 @ stress
transformed_stress

⎡-11309.34089⎤
⎢            ⎥
⎢-11305.80159⎥
⎢            ⎥
⎣-11315.06932⎦

In [13]:
s1, s2, s3 = transformed_stress
vm = sp.sqrt(1/2*( (s1 - s2)**2 + (s2 - s3)**2  + (s3 - s1)**2 ) )
vm

8.10038190790365

In [88]:
sigma_Y = sp.Symbol('sigma_Y')
P_vm =  sp.Matrix([[1, -0.5, -0.5],
                [-0.5, 1, -0.5],
                [-0.5, -0.5, 1]])
temp_P_vm = sp.MatMul(1/sigma_Y**2, P_vm, evaluate=False)
temp_P_vm, P_vm


⎛     ⎡ 1    -0.5  -0.5⎤  ⎡ 1    -0.5  -0.5⎤⎞
⎜ 1   ⎢                ⎥  ⎢                ⎥⎟
⎜────⋅⎢-0.5   1    -0.5⎥, ⎢-0.5   1    -0.5⎥⎟
⎜   2 ⎢                ⎥  ⎢                ⎥⎟
⎝σ_Y  ⎣-0.5  -0.5   1  ⎦  ⎣-0.5  -0.5   1  ⎦⎠

In [30]:
tot = sp.Transpose(test_0) @ P_vm @ test_0
reg = tot[0,0]
tot/reg, reg, 1/(100)**2

⎛⎡       1.0          -0.503285869726093  -0.489833376160954⎤                 
⎜⎢                                                          ⎥                 
⎜⎢-0.503285869876319   0.97971024423744   -0.499810831705443⎥, 6.6975095381352
⎜⎢                                                          ⎥                 
⎝⎣-0.489833376311103  -0.499810831705469   1.00674370097208 ⎦                 

            ⎞
            ⎟
5e-5, 0.0001⎟
            ⎟
            ⎠

In [33]:
uni_stress = np.array([[1,0,0], [0, 0, 0], [0,0,0]])
dev = uni_stress - 1/3*np.trace(uni_stress)*np.eye(3)
dev

array([[ 0.66666667,  0.        ,  0.        ],
       [ 0.        , -0.33333333,  0.        ],
       [ 0.        ,  0.        , -0.33333333]])

In [35]:
J2 = 1/2*np.trace( np.dot(dev, dev) )
J2

0.33333333333333337

In [36]:
r = np.sqrt(2*J2)
r

0.816496580927726

In [76]:
eq = sp.Matrix(((array([[0.01332133]]))/((array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + X_0)/(array([[0.01332133]]) + array([[0.01332133]])) ) ) * (array([[-1.95664328, -2.18063358, -1.86409471],
       [-2.18063358, -1.86455281, -1.95751611],
       [-1.86409471, -1.95751611, -2.18104853]])))*(666 + 9999*X_0)
eq.subs({X_0: 0}).inv() @ np.array([1.725460300683472425e+01,-6.439505508593788363e+01,4.714045207910315582e+01])

array([66.6454090365489, -34.9314120101481, -31.6994481556112],
      dtype=object)

In [77]:
def vm_from_vector(vector):
    s1, s2, s3 = vector
    return np.sqrt( 1/2 * (  (s1 - s2)**2 + (s2-s3)**2 + (s1 - s3)**2 ))
vm_from_vector(np.array([1.725460300683472425e+01,-6.439505508593788363e+01,4.714045207910315582e+01]))

99.99999999999999

In [78]:
temp = eq.subs({X_0: 0}).inv() @ np.array([1.725460300683472425e+01,-6.439505508593788363e+01,4.714045207910315582e+01])
vm_from_vector(np.array(temp.tolist(), dtype=float))

100.00001775113869

In [95]:
test = ((array([[0.01332133]]))/((array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + X_0)/(array([[0.01332133]]) + array([[0.01332133]])) ) ) * (array([[-1.95664328, -2.18063358, -1.86409471],
       [-2.18063358, -1.86455281, -1.95751611],
       [-1.86409471, -1.95751611, -2.18104853]]))
sp.simplify(test)

⎡   -0.0260650908251624        -0.0290489395282614        -0.0248322207831643 
⎢─────────────────────────  ─────────────────────────  ───────────────────────
⎢37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2
⎢                                                                             
⎢   -0.0290489395282614        -0.0248383232844373        -0.0260767180816263 
⎢─────────────────────────  ─────────────────────────  ───────────────────────
⎢37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2
⎢                                                                             
⎢   -0.0248322207831643        -0.0260767180816263        -0.0290544672141449 
⎢─────────────────────────  ─────────────────────────  ───────────────────────
⎣37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2

  ⎤
──⎥
.5⎥
  ⎥
  ⎥
──⎥
.5⎥
  ⎥
  ⎥
──⎥
.5⎦