In [25]:
import sympy as sp
from numpy import array
import numpy as np
from sympy import init_printing
init_printing(use_latex='mathjax')


In [4]:
X_0 = sp.Symbol('X_0')
full_eq = array([[-11.31505478, -11.30934089, -11.3056795 ],
       [-11.30934089, -11.30580159, -11.31506932],
       [-11.3056795 , -11.31506932, -11.30923414]]) + (array([[-2635.96208838, -2636.11483912, -2636.03756048],
       [-2636.11483912, -2636.03364763, -2635.95814545],
       [-2636.03756048, -2635.95814545, -2636.11479851]])) * (X_0)
full_eq

array([[-2635.96208838*X_0 - 11.31505478,
        -2636.11483912*X_0 - 11.30934089,
        -2636.03756048*X_0 - 11.3056795],
       [-2636.11483912*X_0 - 11.30934089,
        -2636.03364763*X_0 - 11.30580159,
        -2635.95814545*X_0 - 11.31506932],
       [-2636.03756048*X_0 - 11.3056795,
        -2635.95814545*X_0 - 11.31506932,
        -2636.11479851*X_0 - 11.30923414]], dtype=object)

In [6]:
test = sp.Matrix(full_eq)
test

⎡-2635.96208838⋅X₀ - 11.31505478  -2636.11483912⋅X₀ - 11.30934089  -2636.03756
⎢                                                                             
⎢-2636.11483912⋅X₀ - 11.30934089  -2636.03364763⋅X₀ - 11.30580159  -2635.95814
⎢                                                                             
⎣-2636.03756048⋅X₀ - 11.3056795   -2635.95814545⋅X₀ - 11.31506932  -2636.11479

048⋅X₀ - 11.3056795 ⎤
                    ⎥
545⋅X₀ - 11.31506932⎥
                    ⎥
851⋅X₀ - 11.30923414⎦

In [18]:
test_0 = test.subs({X_0: 0})
test_0

⎡-11.31505478  -11.30934089  -11.3056795 ⎤
⎢                                        ⎥
⎢-11.30934089  -11.30580159  -11.31506932⎥
⎢                                        ⎥
⎣-11.3056795   -11.31506932  -11.30923414⎦

In [8]:
stress = sp.Matrix([0, 1000, 0])

In [19]:
transformed_stress = test_0 @ stress
transformed_stress

⎡-11309.34089⎤
⎢            ⎥
⎢-11305.80159⎥
⎢            ⎥
⎣-11315.06932⎦

In [13]:
s1, s2, s3 = transformed_stress
vm = sp.sqrt(1/2*( (s1 - s2)**2 + (s2 - s3)**2  + (s3 - s1)**2 ) )
vm

8.10038190790365

In [88]:
sigma_Y = sp.Symbol('sigma_Y')
P_vm =  sp.Matrix([[1, -0.5, -0.5],
                [-0.5, 1, -0.5],
                [-0.5, -0.5, 1]])
temp_P_vm = sp.MatMul(1/sigma_Y**2, P_vm, evaluate=False)
temp_P_vm, P_vm


⎛     ⎡ 1    -0.5  -0.5⎤  ⎡ 1    -0.5  -0.5⎤⎞
⎜ 1   ⎢                ⎥  ⎢                ⎥⎟
⎜────⋅⎢-0.5   1    -0.5⎥, ⎢-0.5   1    -0.5⎥⎟
⎜   2 ⎢                ⎥  ⎢                ⎥⎟
⎝σ_Y  ⎣-0.5  -0.5   1  ⎦  ⎣-0.5  -0.5   1  ⎦⎠

In [30]:
tot = sp.Transpose(test_0) @ P_vm @ test_0
reg = tot[0,0]
tot/reg, reg, 1/(100)**2

⎛⎡       1.0          -0.503285869726093  -0.489833376160954⎤                 
⎜⎢                                                          ⎥                 
⎜⎢-0.503285869876319   0.97971024423744   -0.499810831705443⎥, 6.6975095381352
⎜⎢                                                          ⎥                 
⎝⎣-0.489833376311103  -0.499810831705469   1.00674370097208 ⎦                 

            ⎞
            ⎟
5e-5, 0.0001⎟
            ⎟
            ⎠

In [33]:
uni_stress = np.array([[1,0,0], [0, 0, 0], [0,0,0]])
dev = uni_stress - 1/3*np.trace(uni_stress)*np.eye(3)
dev

array([[ 0.66666667,  0.        ,  0.        ],
       [ 0.        , -0.33333333,  0.        ],
       [ 0.        ,  0.        , -0.33333333]])

In [35]:
J2 = 1/2*np.trace( np.dot(dev, dev) )
J2

0.33333333333333337

In [36]:
r = np.sqrt(2*J2)
r

0.816496580927726

In [76]:
eq = sp.Matrix(((array([[0.01332133]]))/((array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + X_0)/(array([[0.01332133]]) + array([[0.01332133]])) ) ) * (array([[-1.95664328, -2.18063358, -1.86409471],
       [-2.18063358, -1.86455281, -1.95751611],
       [-1.86409471, -1.95751611, -2.18104853]])))*(666 + 9999*X_0)
eq.subs({X_0: 0}).inv() @ np.array([1.725460300683472425e+01,-6.439505508593788363e+01,4.714045207910315582e+01])

array([66.6454090365489, -34.9314120101481, -31.6994481556112],
      dtype=object)

In [77]:
def vm_from_vector(vector):
    s1, s2, s3 = vector
    return np.sqrt( 1/2 * (  (s1 - s2)**2 + (s2-s3)**2 + (s1 - s3)**2 ))
vm_from_vector(np.array([1.725460300683472425e+01,-6.439505508593788363e+01,4.714045207910315582e+01]))

99.99999999999999

In [78]:
temp = eq.subs({X_0: 0}).inv() @ np.array([1.725460300683472425e+01,-6.439505508593788363e+01,4.714045207910315582e+01])
vm_from_vector(np.array(temp.tolist(), dtype=float))

100.00001775113869

In [95]:
test = ((array([[0.01332133]]))/((array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + array([[0.01332133]]) + X_0)/(array([[0.01332133]]) + array([[0.01332133]])) ) ) * (array([[-1.95664328, -2.18063358, -1.86409471],
       [-2.18063358, -1.86455281, -1.95751611],
       [-1.86409471, -1.95751611, -2.18104853]]))
sp.simplify(test)

⎡   -0.0260650908251624        -0.0290489395282614        -0.0248322207831643 
⎢─────────────────────────  ─────────────────────────  ───────────────────────
⎢37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2
⎢                                                                             
⎢   -0.0290489395282614        -0.0248383232844373        -0.0260767180816263 
⎢─────────────────────────  ─────────────────────────  ───────────────────────
⎢37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2
⎢                                                                             
⎢   -0.0248322207831643        -0.0260767180816263        -0.0290544672141449 
⎢─────────────────────────  ─────────────────────────  ───────────────────────
⎣37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2.5  37.5337897942623⋅X₀ + 2

  ⎤
──⎥
.5⎥
  ⎥
  ⎥
──⎥
.5⎥
  ⎥
  ⎥
──⎥
.5⎦