In [1]:
import sympy as sp
from numpy import array
import numpy as np
from sympy import init_printing
init_printing(use_latex='mathjax')


In [2]:
X_0 = sp.Symbol('X_0')
full_eq =  (array([[ 1.91357426e-01, -2.99208983e-08,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-2.99208983e-08,  6.59119893e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  8.50477443e-02,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.50477443e-02,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  4.25238734e-02]])) * ((array([[2.44813553e-11]]))/(((array([[0.01010114]]) + X_0) * (array([[0.01010114]]) + X_0)) * ((array([[0.01010114]]) + X_0) * (array([[0.01010114]]) + X_0))) )
full_eq

array([[4.68468913519946e-12/(X_0 + 0.01010114)**4,
        -7.32504142177466e-19/(X_0 + 0.01010114)**4, 0, 0, 0],
       [-7.32504142177466e-19/(X_0 + 0.01010114)**4,
        1.6136148285831e-11/(X_0 + 0.01010114)**4, 0, 0, 0],
       [0, 0, 2.08208404567185e-12/(X_0 + 0.01010114)**4, 0, 0],
       [0, 0, 0, 2.08208404567185e-12/(X_0 + 0.01010114)**4, 0],
       [0, 0, 0, 0, 1.04104205343762e-12/(X_0 + 0.01010114)**4]],
      dtype=object)

In [3]:
test = sp.Matrix(full_eq)
test

⎡ 4.68468913519946e-12   -7.32504142177466e-19                                
⎢ ────────────────────   ──────────────────────           0                   
⎢                   4                       4                                 
⎢  (X₀ + 0.01010114)       (X₀ + 0.01010114)                                  
⎢                                                                             
⎢-7.32504142177466e-19    1.6136148285831e-11                                 
⎢──────────────────────   ───────────────────             0                   
⎢                   4                       4                                 
⎢  (X₀ + 0.01010114)       (X₀ + 0.01010114)                                  
⎢                                                                             
⎢                                                2.08208404567185e-12         
⎢          0                       0             ────────────────────         
⎢                                                   

In [4]:
test_0 = test.subs({X_0: 0.00})
test_0

⎡0.000449986221398551   -7.03604362177579e-11           0                     
⎢                                                                             
⎢-7.03604362177579e-11   0.0015499522349328             0                     
⎢                                                                             
⎢          0                      0            0.000199993874792333           
⎢                                                                             
⎢          0                      0                     0            0.0001999
⎢                                                                             
⎣          0                      0                     0                     

0                     0         ⎤
                                ⎥
0                     0         ⎥
                                ⎥
0                     0         ⎥
                                ⎥
93874792333           0         ⎥
                                ⎥
0            9.9

In [5]:
M_upgrade = np.zeros(((6,6)))
M_upgrade[1:, 1:] = test_0
M_upgrade

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.49986221e-04, -7.03604362e-11,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -7.03604362e-11,  1.54995223e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.99993875e-04,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.99993875e-04,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  9.99969403e-05]])

In [6]:
sqrt2 = np.sqrt(2)
sqrt3 = np.sqrt(3)
d = 1./np.sqrt(6) * np.array( [[ sqrt2, sqrt2, sqrt2, 0, 0, 0  ],
                                   [ -1, -1, 2, 0, 0, 0],
                                   [-sqrt3, sqrt3, 0, 0, 0, 0],
                                   [0, 0, 0, 2*sqrt3, 0, 0],
                                   [0, 0, 0, 0, 2*sqrt3, 0],
                                   [0, 0, 0, 0, 0, 2*sqrt3] ])
d_inv = 1/np.sqrt(6) * np.array( [[ sqrt2, -1, -sqrt3, 0, 0, 0  ],
                                   [ sqrt2, -1, sqrt3, 0, 0, 0],
                                   [ sqrt2, 2, 0, 0, 0, 0],
                                   [0, 0, 0, sqrt3, 0, 0],
                                   [0, 0, 0, 0, sqrt3, 0],
                                   [0, 0, 0, 0, 0, sqrt3] ])
real_space = d.T @ M_upgrade @ d
real_space

array([[ 0.00084997, -0.00069998, -0.00015   ,  0.        ,  0.        ,
         0.        ],
       [-0.00069998,  0.00084997, -0.00015   ,  0.        ,  0.        ,
         0.        ],
       [-0.00015   , -0.00015   ,  0.00029999,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.00039999,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.00039999,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.00019999]])

In [7]:
H = 7
G = 1.5
F = 1.5
N = 1
L = 2
M = 2
P = np.array( [ [ G+H, -H, -G, 0, 0, 0 ],
                [-H, F+H, -F, 0,0,0],
                 [-G, -F, F+G, 0, 0, 0],
                  [0,0,0, 2*L, 0, 0],
                   [0,0,0,0, 2*M, 0],
                    [0,0,0,0,0,2*N] ])
number_of_eqps = 6
eqpses = np.linspace(0, 0.05, number_of_eqps)
for eqps in eqpses:
    P_analytical = P/(10 + 990*eqps)**4
    print(P_analytical)

[[ 0.00085 -0.0007  -0.00015  0.       0.       0.     ]
 [-0.0007   0.00085 -0.00015  0.       0.       0.     ]
 [-0.00015 -0.00015  0.0003   0.       0.       0.     ]
 [ 0.       0.       0.       0.0004   0.       0.     ]
 [ 0.       0.       0.       0.       0.0004   0.     ]
 [ 0.       0.       0.       0.       0.       0.0002 ]]
[[ 5.42009152e-05 -4.46360478e-05 -9.56486739e-06  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.46360478e-05  5.42009152e-05 -9.56486739e-06  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-9.56486739e-06 -9.56486739e-06  1.91297348e-05  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.55063131e-05
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.55063131e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.27531565e-05]]
[[ 1.07783894e-05 -8.87632068e-06 -1.90206872e-06 