In [1]:
import numpy as np

In [2]:
def align_pi_plane_with_axes_rot():
    """
    Returns a matrix that rotates the pi plane's normal to be the z axis
    i.e., a slice of pi plane becomes the xy plane after rotation
    """
    pi_vector = np.array([1, 1, 1]) / np.sqrt(3.)
    # wanted_vector = np.array([1, 0, 0])
    wanted_vector = np.array([0, 0, 1])
    wanted_vector = wanted_vector / np.linalg.norm(wanted_vector)
    added = (pi_vector + wanted_vector).reshape([-1, 1])
    # from Rodrigues' rotation formula, more info here: https://math.stackexchange.com/a/2672702
    rot_mat = 2 * (added @ added.T) / (added.T @ added) - np.eye(3)
    return rot_mat


In [3]:
d = align_pi_plane_with_axes_rot()
d, np.linalg.inv(d)

(array([[-0.78867513,  0.21132487,  0.57735027],
        [ 0.21132487, -0.78867513,  0.57735027],
        [ 0.57735027,  0.57735027,  0.57735027]]),
 array([[-0.78867513,  0.21132487,  0.57735027],
        [ 0.21132487, -0.78867513,  0.57735027],
        [ 0.57735027,  0.57735027,  0.57735027]]))

# Test the two methods

In [4]:
P_vm = np.array([[1, -0.5, -0.5],
                     [-0.5, 1, -0.5],
                     [-0.5, -0.5, 1]])
P_vm_pi_plane = d @ P_vm @ d
P_vm_pi_plane, d @ P_vm_pi_plane @ d

(array([[ 1.50000000e+00, -5.79375858e-17,  5.30847167e-17],
        [-5.79375858e-17,  1.50000000e+00,  5.30847167e-17],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]),
 array([[ 1. , -0.5, -0.5],
        [-0.5,  1. , -0.5],
        [-0.5, -0.5,  1. ]]))

In [5]:
X11, X12, X22, X13, X23, X33 = (np.random.random(1)[0], np.random.random(1)[0], np.random.random(1)[0], np.random.random(1)[0], np.random.random(1)[0], np.random.random(1)[0])
A_rand = np.eye(3) #np.array([ [ X11, X12, X13 ], [ X12, X22, X23 ], [ X13, X23, X33 ] ])
A_rand, np.linalg.eigvals(A_rand)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([1., 1., 1.]))

# Method One: Original

In [23]:
d_A = d @ A_rand @ d
d_A[:,2] = 0
d_A[2,:] = 0
d_A[2,2] = 1
d_A

array([[ 1.00000000e+00, -7.56324913e-17,  0.00000000e+00],
       [-7.56324913e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [24]:
dd_A = d @ d_A @ d
dd_A
dd_A, np.linalg.norm(dd_A[:,2])

(array([[ 1.00000000e+00, -1.31143643e-16,  3.53898111e-17],
        [-1.31143643e-16,  1.00000000e+00,  3.53898111e-17],
        [ 3.53898111e-17,  3.53898111e-17,  1.00000000e+00]]),
 0.9999999999999999)

In [25]:
P_real_orig = dd_A.T @ P_vm @ dd_A
P_real_orig

array([[ 1. , -0.5, -0.5],
       [-0.5,  1. , -0.5],
       [-0.5, -0.5,  1. ]])

# Method 2: Other Way Around

In [9]:
red_P_vm_pi = P_vm_pi_plane
red_P_vm_pi

array([[ 1.50000000e+00, -5.79375858e-17,  5.30847167e-17],
       [-5.79375858e-17,  1.50000000e+00,  5.30847167e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [26]:
d_A_red = d_A
d_A_red

array([[ 1.00000000e+00, -7.56324913e-17,  0.00000000e+00],
       [-7.56324913e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [27]:
red_P_real_pi = d_A_red.T @ red_P_vm_pi @ d_A_red
red_P_real_pi

array([[ 1.50000000e+00, -2.84835060e-16,  5.30847167e-17],
       [-2.84835060e-16,  1.50000000e+00,  5.30847167e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [29]:
P_real_orig, d @ red_P_real_pi @ d

(array([[ 1. , -0.5, -0.5],
        [-0.5,  1. , -0.5],
        [-0.5, -0.5,  1. ]]),
 array([[ 1. , -0.5, -0.5],
        [-0.5,  1. , -0.5],
        [-0.5, -0.5,  1. ]]))